MVCProject/MVC-Project/PresentationLayer/Controllers/DepartmentController.cs
using BusinessLogicLayer.Interfaces;
using BusinessLogicLayer.Repositories;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork UnitOfWork;

        public DepartmentController(IUnitOfWork UnitOfWork)
        {
            this.UnitOfWork = UnitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var departments = await UnitOfWork.DepartmentRepository.GetAllAsync();
            return View(departments);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Department department)
        {
            if (!ModelState.IsValid) // Server Side Validation
                return View(department); // return the same view but with the error messages

            await UnitOfWork.DepartmentRepository.AddAsync(department);
            await UnitOfWork.CompleteAsync();
            TempData["Message"] = "Department is created"; // transfer data from action to action.
            return RedirectToAction(nameof(Index));
        }

        /*
         Details is the same as Edit but one is read only and the other can be edited
         */
        public async Task<IActionResult> Details(int? id, bool Writable = false)
        {
            if (id is null)
                return BadRequest();

            var department = await UnitOfWork.DepartmentRepository.GetByEntryIdAsync(id.Value);

            if (department is null)
                return NotFound();

            if (Writable)
                return View("Edit", department);

            return View("Details", department);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return BadRequest();

            return await Details(id.Value, true);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Department department, [FromRoute] int id)
        {
            // Useless
            if (id != department.Id)
                return BadRequest();


            if (!ModelState.IsValid)
                return View(department);

            try
            {
                UnitOfWork.DepartmentRepository.Update(department);
                await UnitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception ex)
            {
                // Log exceptions 
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(department);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
                return BadRequest();

            var depatment = await UnitOfWork.DepartmentRepository.GetByEntryIdAsync(id.Value);

            if (depatment is null) return NotFound();

            return View(depatment);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Department department)
        {
            if (department is null) return NotFound();

            try
            {
                UnitOfWork.DepartmentRepository.Delete(department);
                await UnitOfWork.CompleteAsync();
            }
            catch
            {
                return View(department);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

MVCProject/MVC-Project/PresentationLayer/Controllers/EmployeeController.cs
using AutoMapper;
using BusinessLogicLayer.Interfaces;
using BusinessLogicLayer.Repositories;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PresentationLayer.Helpers;
using PresentationLayer.Models;
using System.Collections;
using System.Collections.Generic;
using System.Reflection.Metadata;
using System.Threading.Tasks;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork UnitOfWork;
        private readonly IMapper mapper;

        public EmployeeController(IUnitOfWork UnitOfWork, IMapper mapper)
        {
            this.UnitOfWork = UnitOfWork;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index(string Name)
        {
            IEnumerable<Employee> employees;
            if (Name is null)
                employees = await UnitOfWork.EmployeeRepository.GetAllAsync();
            else
                employees = UnitOfWork.EmployeeRepository.GetEmployeesByName(Name);

            IEnumerable<EmployeeViewModel> employeesViewModel = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);

            ViewData["Message"] = "Hello from view data"; // Dictionary<string, object>
            ViewBag.Message = "Hello from view bag"; // Dynamic, Will override the message value.
            return View(employeesViewModel);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Departments = new SelectList(await UnitOfWork.DepartmentRepository.GetAllAsync(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employeeViewModel)
        {
            if (!ModelState.IsValid) // Server Side Validation
                return View(employeeViewModel); // return the same view but with the error messages

            // Here we need mapping from Employee to EmployeeViewModel with many ways such as:
            // 1- Manual mapping.
            // 2- Explicit casting (which will need operator overloading) and inside it we will use manual mapping
            // 3- AutoMapper Package.

            employeeViewModel.ImageName = DocumentSettings.UploadFile(employeeViewModel.Image, "Images");
            Employee employee = mapper.Map<EmployeeViewModel, Employee>(employeeViewModel);
            await UnitOfWork.EmployeeRepository.AddAsync(employee);
            await UnitOfWork.CompleteAsync();
            return RedirectToAction(nameof(Index));
        }

        /*
         Details is the same as Edit but one is read only and the other can be edited
         */
        public async Task<IActionResult> Details(int? id, bool Writable = false)
        {
            if (id is null)
                return BadRequest();

            var employee = UnitOfWork.EmployeeRepository.GetByEntryIdAsync(id.Value).Result;

            if (employee is null)
                return NotFound();
            var employeeViewModel = mapper.Map<Employee, EmployeeViewModel>(employee);

            ViewBag.Departments = new SelectList(await UnitOfWork.DepartmentRepository.GetAllAsync(), "Id", "Name");

            if (Writable)
                return View("Edit", employeeViewModel);

            return View("Details", employeeViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return BadRequest();

            return await Details(id.Value, true);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeViewModel employeeViewModel, [FromRoute] int id)
        {
            // Useless
            if (id != employeeViewModel.Id)
                return BadRequest();


            if (!ModelState.IsValid)
                return View(employeeViewModel);

            try
            {
                if (employeeViewModel.Image is not null)
                {
                    DocumentSettings.DeleteFile(employeeViewModel.ImageName, "Images");
                    employeeViewModel.ImageName = DocumentSettings.UploadFile(employeeViewModel.Image, "Images");
                }
                var employee = mapper.Map<EmployeeViewModel, Employee>(employeeViewModel);
                UnitOfWork.EmployeeRepository.Update(employee);
                await UnitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception ex)
            {
                // Log exceptions 
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(employeeViewModel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
                return BadRequest();

            var employee = await UnitOfWork.EmployeeRepository.GetByEntryIdAsync(id.Value);

            if (employee is null) return NotFound();

            var employeeViewModel = mapper.Map<Employee, EmployeeViewModel>(employee);

            return View(employeeViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EmployeeViewModel employeeViewModel)
        {
            if (employeeViewModel is null) return NotFound();
            var employee = mapper.Map<EmployeeViewModel, Employee>(employeeViewModel);
            try
            {
                UnitOfWork.EmployeeRepository.Delete(employee);
                await UnitOfWork.CompleteAsync();
                if (employeeViewModel.ImageName is not null)
                    DocumentSettings.DeleteFile(employeeViewModel.ImageName, "Images");
            }
            catch
            {
                return View(employeeViewModel);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

MVCProject/MVC-Project/PresentationLayer/Views/Shared/ButtonsPartialView.cshtml
@model int

<td> <a asp-action="Details" asp-route-id="@Model"> <i class="fas fa-eye">  </i> </a> </td>
<td> <a asp-action="Edit" asp-route-id="@Model"> <i class="fas fa-edit">  </i> </a> </td>
<td> <a asp-action="Delete" asp-route-id="@Model"> <i class="fas fa-trash">  </i> </a> </td>

MVCProject/MVC-Project/PresentationLayer/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title> @ViewData["Title"] </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/css/authstylesheet.css" rel="stylesheet" />
</head>

<body>
    <!-- main -->
    <div class="main-w3layouts wrapper">
        <h1> @ViewData["Title"]</h1>

        @RenderBody()

        <ul class="colorlib-bubbles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>
    <!-- //main -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("validateSection", required: false)
</body>
</html>9

MVCProject/MVC-Project/PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PresentationLayer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index"> Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index"> Employees</a>
                        </li>
                        <li class="nav-item ml-auto" >
                            <a class="nav-link text-danger" asp-area="" asp-controller="Account" asp-action="Signout"> Sign out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("validateSection", required: false)
</body>
</html>